<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "create-your-own-content": {
        "title": "Create your own content",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2019-05-21 21:55:43",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "10a4a9b28168b43b24618025bfc2697f",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "set-up-your-new-site": {
        "title": "Set up your new site",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2019-05-21 21:54:43",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "bd3ef97fad049db19f3dd74c26de703e",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "follow-bludit": {
        "title": "Follow Bludit",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2019-05-21 21:53:43",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "b801a558fc983d427649215e07218223",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "about": {
        "title": "About",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "static",
        "date": "2019-05-21 21:52:43",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "1cf49a83c32a0f0be4507ddefbdfd861",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    }
}